### ISSUE TITLE
Apps

### ISSUE THREAD

**Issue by 1234abc5678** [Radon-Games/Radon-Games#86] opened 2023-02-27 02:35 UTC
### Describe the bug

When you try clicking on google or youtube or any of the other apps, they don't work, instead they show "Error processing your request"

### Steps To Reproduce

Go to the apps page at the top
Click it and then click google
Then it should show you the error page

### Expected behavior

I expect that this should be able to be fixed since it seems like something is just typed in wrong or something like that

**Comment by 1234abc5678** [comment] 2023-03-02 03:40
I dont know if anyone say this, but I just checked and it still dosent work

**Comment by cohenerickson** [comment] 2023-03-02 03:46
I am unable to reproduce this at all, can you send a screenshot of the error your are getting?

**Comment by 1234abc5678** [comment] 2023-03-02 03:52
sure
![Screenshot 2023-03-01 8 50 52 PM](https://user-images.githubusercontent.com/126031106/222326759-d5697a52-22e4-4ea0-8b71-a4c7992423db.png)

**Comment by cohenerickson** [comment] 2023-03-04 17:33
Fixed in 26b60e9

**Closed by cohenerickson** 2023-03-04 17:33 UTC
Labels: bug
