### ISSUE TITLE
Roblox Doesn't work.

### ISSUE THREAD

**Issue by STEEPERCREVE** [Radon-Games/Radon-Games#21] opened 2022-09-27 19:45 UTC
Describe the bug
Roblox does not work on your site and says the game is unavailable.

To Reproduce

Go to 'Your game site (i went there through Nebula'
Click on 'Games'
Scroll down to 'Roblox'
See error
Expected behavior
I expected roblox to run, however, it just goes to your site inside the i-frame and says it isn't available.

Screenshots

Desktop (please complete the following information):

OS: [macOS 12.2.1 (Build 21D62)]
Browser [Chrome]
Version [105.0.5195.125 (Official Build)]
Smartphone (please complete the following information):

Additional context
I just wished it worked. I hope it's easily fixable as I need to use a proxy on my wifi, however, when I use now.gg's proxy link it doesn't allow me and just gives me another link. Thanks!

**Comment by cohenerickson** [comment] 2022-11-15 17:14
duplicate of #25

**Closed** 2022-11-15 17:15 UTC
Labels: bug
