### ISSUE TITLE
Game request:pubg

### ISSUE THREAD

**Issue by Vegarobert54** [Radon-Games/Radon-Games#8] opened 2022-07-08 22:48 UTC
Pubg Mobile Now gg

Pubg has is a battle royale first person shooter and third person. It also has some arcade modes like gun game.

https://now.gg/apps/proxima-beta/2609/pubg-mobile-resistance.html

**Comment by cohenerickson** [comment] 2022-07-08 22:53
Duplicate of #7

**Closed by cohenerickson** 2022-07-08 22:53 UTC
Labels: duplicate, game request
