### ISSUE TITLE
Add a Flash Opener

### ISSUE THREAD

**Issue by The-Rock-21** [Radon-Games/Radon-Games#117] opened 2023-10-25 21:08 UTC
Add flash opener.
(Tried to use ChatGPT to convince this guy. It didn't work. So kids remember, don't use ChatGPT to do your work for you)

**Comment by The-Entity-Aka-Backroom-69** [comment] 2023-10-25 21:12
Can you add a flash opener tho?

**Comment by Notplayingallday383** [comment] 2023-10-25 21:25
just use ruffle lol or if its blocked just use the proxy to access [ruffle](https://ruffle.rs/demo)

**Comment by The-Rock-21** [comment] 2023-10-25 21:33
Using a proxy to access ruffle makes ruffle run slower.

**Comment by cohenerickson** [comment] 2023-11-10 14:46
duplicate of #91

**Closed by cohenerickson** 2023-11-10 14:46 UTC
Labels: enhancement
