### ISSUE TITLE
New game that should be in

### ISSUE THREAD

**Issue by Trueawolf578** [Radon-Games/Radon-Games#36] opened 2022-10-31 14:59 UTC
**Name of Game**
bloons tower defense 5

**Description**
It's a game where a couple of monkeys would shoot, throw, or destroy balloons.

**URL**
Ninjakiwi.com.

**Additional information**
Add any other information about the game here.

**Comment by cohenerickson** [comment] 2023-11-08 23:49
duplicate of #38

**Closed by cohenerickson** 2023-11-08 23:49 UTC
Labels: game request
