### ISSUE TITLE
super smash flash 2

### ISSUE THREAD

**Issue by sonicman1234** [Radon-Games/Radon-Games#17] opened 2022-09-14 22:11 UTC
**Name of Game**
The name of the game you want to request.

**Description**
A brief description of the game (so we add the right one).

**URL**
The URL of the game's website or a playable version of the game.

**Additional information**
Add any other information about the game here.

**Comment by cohenerickson** [comment] 2023-11-09 02:30
duplicate of #66

**Closed by cohenerickson** 2023-11-09 02:30 UTC
Labels: game request

**Comment by sonicman1234** [comment] 2023-11-09 02:51
so like how do i access super smash flash 2
